#!/bin/bash

#
#   sh start.sh
#
source ~/.bashrc

export DB_NAME=/var/lib/drop/db/node_collector.db
export FLOWS_DIR=/var/lib/drop/flows
export LOGS_DIR=/var/lib/drop/logs
export DROP_HOME=/opt/drop-core
export DROP_REPO="drop-master"
export PORT=8082
export API_PORT=8081

exec /opt/drop-pyenv/bin/uwsgi --ini uwsgi.ini 
