#!/bin/sh

cp /opt/drop-gateway-api/conf/drop-gateway-api.service /etc/systemd/system/ && systemctl daemon-reload
systemctl enable drop-gateway-api

## start service
systemctl restart drop-gateway-api
